#pragma once

namespace Ace
{
    enum class TokenKind
    {
        EndOfFile,

        Colon,
        ColonColon,
        Semicolon,
        Comma,
        Exclamation,
        Tilde,
        Dot,
        MinusGreaterThan,

        OpenParen,
        CloseParen,
        OpenBrace,
        CloseBrace,
        OpenBracket,
        CloseBracket,

        Ident,

        Int8,
        Int16,
        Int32,
        Int64,
        
        UInt8,
        UInt16,
        UInt32,
        UInt64,
        
        Int,

        Float32,
        Float64,

        String,
        Bool,

        Equals,
        EqualsEquals,
        ExclamationEquals,
        Plus,
        PlusEquals,
        Minus,
        MinusEquals,
        Asterisk,
        AsteriskEquals,
        Slash,
        SlashEquals,
        Percent,
        LessThan,
        GreaterThan,
        LessThanEquals,
        GreaterThanEquals,
        LessThanLessThan,
        GreaterThanGreaterThan,

        Caret,
        Ampersand,
        VerticalBar,
        AmpersandAmpersand,
        VerticalBarVerticalBar,
        PercentEquals,
        LessThanLessThanEquals,
        GreaterThanGreaterThanEquals,
        AmpersandEquals,
        CaretEquals,
        VerticalBarEquals,

        AddressOfKeyword,
        SizeOfKeyword,
        DerefAsKeyword,
        IfKeyword,
        ElseKeyword,
        ElifKeyword,
        WhileKeyword,
        ModuleKeyword,
        ReturnKeyword,
        TraitKeyword,
        StructKeyword,
        OpKeyword,
        PublicKeyword,
        ExternKeyword,
        CastKeyword,
        ExitKeyword,
        AssertKeyword,
        ImplKeyword,
        BoxKeyword,
        UnboxKeyword,
        TrueKeyword,
        FalseKeyword,
        IntKeyword,
        Int8Keyword,
        Int16Keyword,
        Int32Keyword,
        Int64Keyword,
        UInt8Keyword,
        UInt16Keyword,
        UInt32Keyword,
        UInt64Keyword,
        Float32Keyword,
        Float64Keyword,
        BoolKeyword,
        VoidKeyword,
    };
}
